### ISSUE TITLE
matrix calculator is wrong

### ISSUE THREAD

**Issue by Curry30huang** [OrangeX4/Latex-Sympy-Calculator#10]
\begin{bmatrix}1\\2\\3\end{bmatrix}\begin{bmatrix}1&2&3\end{bmatrix}
the true answer is a n*n matrix, but the result is \begin{bmatrix}6\\12\\18\end{bmatrix}
It is absolutely wrong. This plugin will translate 1 & 2 & 3 to 6 in matrix. This is the key bug.
Can you solve this problem. 
Thank you
![Snipaste_2022-04-01_23-07-02](https://user-images.githubusercontent.com/68208371/161290808-c2f783e5-bcbd-405e-b512-401f12aed80e.png)
!

**Comment by OrangeX4** [comment]
I am sorry to forget to test it.

You can use `pip install --upgrade latex2sympy2` to update the module and fix the bug.

**Comment by Curry30huang** [comment]
Thank you very much!
The problem was solved!
Everything is ok now.

---Original---
From: ***@***.***&gt;
Date: Sat, Apr 2, 2022 09:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OrangeX4/Latex-Sympy-Calculator] matrix calculator is wrong(Issue #10)




 
I am sorry to forget to test it.
 
You can use pip install --upgrade latex2sympy2 to update the module and fix the bug.
