### ISSUE TITLE
Elementary Transformation

### ISSUE THREAD

**Issue by Darkhell101** [OrangeX4/Latex-Sympy-Calculator#12]
i test how to exchange two rows or columns in a matrix. however, when i code like "r_1 + k r_2" to replace "r_1 \leftrightarrow r_2", a mistake occours. (k is a number)
pls help me.

**Comment by OrangeX4** [comment]
Can you provide a more concrete example?

**Comment by Darkhell101** [comment]
yes,
![image](https://user-images.githubusercontent.com/37462013/162485968-11abaed0-d26e-4a3b-b162-caef55cc051b.png)

**Comment by OrangeX4** [comment]
I have fixed this bug.

You could update your `latex2sympy2` to 1.7.6 by `pip install --upgrade latex2sympy2`.

**Comment by Darkhell101** [comment]
very good!!!!
![image](https://user-images.githubusercontent.com/37462013/162554859-82c36914-2700-4e42-aee5-0dd887c52440.png)

**Comment by Darkhell101** [comment]
![image](https://user-images.githubusercontent.com/37462013/162555427-927665ad-cfba-4081-a5bf-0eef8b9b89af.png)
maybe last question. I want to know whether the last step in the fig is possible.

**Comment by OrangeX4** [comment]
It is impossible, because subscription is incalculable.

**Comment by Darkhell101** [comment]
Ok, very helpful 👍



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 9, 2022 12:12 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [OrangeX4/Latex-Sympy-Calculator] Elementary Transformation (Issue #12)




 
It is impossible, because subscription is incalculable.

**Comment by OrangeX4** [comment]
But you can use it like:

```markdown
Define by `Ctrl + Shift + Alt + D`
$B_{i} = \begin{bmatrix} i + 1 & i + 2 & i + 3 \\\end{bmatrix}$

$\sum_{i=1}^{3}B_{i} = \begin{bmatrix}9 & 12 & 15\end{bmatrix}$
```

![](https://picgo-1258602555.cos.ap-nanjing.myqcloud.com/20220409130102.png)

**Comment by Darkhell101** [comment]
Hi, I get similar problem.
![image](https://user-images.githubusercontent.com/37462013/162665561-e733da60-2249-4e0c-bc0a-84eab4da4bcf.png)

**Comment by OrangeX4** [comment]
You must use grammar like "r_k +/– ...".

The grammer you use is not supported.

**Comment by Darkhell101** [comment]
> 

Ok
