### ISSUE TITLE
matrics multiplay error

### ISSUE THREAD

**Issue by Darkhell101** [OrangeX4/Latex-Sympy-Calculator#13]
![image](https://user-images.githubusercontent.com/37462013/168092628-033c556d-a4bd-4278-b748-18fe49edcd5d.png)

As you can see, the result of A^Tb is wrong.
if I change A into real latex code instead of assigning  A  as a Matrix, it can be fine.

advice:
preset some special matrix like I for identity matrix

**Comment by OrangeX4** [comment]
It is limit of SymPy itself and it is hard to fix it.

Sympy can not make sure that A and b is symbol of matrix and it be consider as a number.

You can press `Shift + Ctrl + Alt + R` to replace symbols `A` and `b` by youself, and then select all to calculate it.

For your advice, it is also hard to implement it because it is necessary  to define the concrete size of matrix I in SymPy, but it is hard to know the concrete size of I advancely.

**Comment by Darkhell101** [comment]
I&nbsp;see.&nbsp;very&nbsp;helpful.&nbsp;thanks


---Original---
From: ***@***.***&gt;
Date: Thu, May 12, 2022 22:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OrangeX4/Latex-Sympy-Calculator] matrics multiplay error (Issue#13)




 
It is limit of SymPy itself and it is hard to fix it.
 
&mdash;

**Comment by OrangeX4** [comment]
I update my reply and you can know the reasons.

**Comment by OrangeX4** [comment]
I have tried to fix the problem, and I use a method to avoid it, so you can calculate it successfully. Besides, I add identity matrix into it, but you must use syntax like `\bm{I}_3` where `3` is the dimension of identity matrix.

You can update your `latex2sympy2` module by `pip install latex2sympy2==1.7.8`.

![image](https://user-images.githubusercontent.com/34951714/168552795-7eddc4f0-f20e-45eb-bd7b-2eb6123f87e3.png)

**Comment by Darkhell101** [comment]
I test some examples. 
\bm{I}_{10} = \bm{I}_{10}
\bm{I}_10 = \bm{I}_{10}
though the len of matrix is usually less than 10, it is a small mistake.

if constant matrix could be added, it will be  more convinient for normal use.
![image](https://user-images.githubusercontent.com/37462013/168621784-6e7d0065-99f7-4c5e-af1e-3f45cc449429.png)

**Comment by OrangeX4** [comment]
It will be a big burden for the extension so I don't plan to add more than 10.



---Original---
From: ***@***.***&gt;
Date: Mon, May 16, 2022 22:55 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [OrangeX4/Latex-Sympy-Calculator] matrics multiplay error (Issue #13)




 
I test some examples.
 \bm{I}{10} = \bm{I}{10}
 \bm{I}10 = \bm{I}{10}
 though the len of matrix is usually less than 10, it is a small mistake.
 
if constant matrix could be added, it will be  more convinient for normal use.

**Comment by Darkhell101** [comment]
agree wiht you. Maybe a designed latex package is better for this idea. Thanks for your wonderful work!
