### ISSUE TITLE
Doesn't understand fractions made with `\over`

### ISSUE THREAD

**Issue by euwbah** [OrangeX4/Latex-Sympy-Calculator#14]
Firstly, thanks for making this amazing plugin. A great addition to streamline latex workflow on vscode.

As for the issue, I tried to run it with `{(3)(4) \over 2\sqrt{4+3(7)}}` as input:

![image](https://user-images.githubusercontent.com/7107290/194883881-bd829725-cd0d-4c6f-b613-1a82767f7210.png)

But resulted in the following error:

![image](https://user-images.githubusercontent.com/7107290/194883852-1a312f8b-088e-45b0-b127-e4249b35834e.png)

Using the `\frac` representation worked fine as usual. It just would be convenient if this was supported as well.

**Comment by OrangeX4** [comment]
Thanks for this suggestion.

I will try to implement this in my spare time.

**Comment by OrangeX4** [comment]
Fixed it.

Update by `pip install latex2sympy2==1.7.9`.
