### ISSUE TITLE
The number of combinations cannot be calculated

### ISSUE THREAD

**Issue by yixing312** [OrangeX4/Latex-Sympy-Calculator#16]
I can not calculate combinations .Maybe there's something wrong with the way I type it.I have tried the following input methods.
1. \begin{pmatrix}
  5 \\
  2 \\
\end{pmatrix}
2. C^2_5
3. {5 \choose 2}
4. \tbinom{5}{2}
I want to get a standard input on the number of combinations

**Comment by OrangeX4** [comment]
try \binom{5}{2}



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 21, 2022 03:00 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [OrangeX4/Latex-Sympy-Calculator] The number of combinations cannotbe calculated (Issue #16)




 
I can not calculate combinations .Maybe there's something wrong with the way I type it.I have tried the following input methods.
  
\begin{pmatrix}
 5 \
 2 \
 \end{pmatrix}
 
C^2_5
 
{5 \choose 2}
 
\tbinom{5}{2}
 I want to get a standard input on the number of combinations

**Comment by yixing312** [comment]
万分感谢


从 Windows 版邮件发送

发件人: OrangeX4
发送时间: 2022年10月21日 9:35
收件人: OrangeX4/Latex-Sympy-Calculator
抄送: yixing312; Author
主题: Re: [OrangeX4/Latex-Sympy-Calculator] The number of combinationscannot be calculated (Issue #16)

try \binom{5}{2} 



---Original--- 
From: ***@***.***&gt; 
Date: Fri, Oct 21, 2022 03:00 AM 
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [OrangeX4/Latex-Sympy-Calculator] The number of combinations cannotbe calculated (Issue #16) 





I can not calculate combinations .Maybe there's something wrong with the way I type it.I have tried the following input methods. 

\begin{pmatrix} 
5 \ 
2 \ 
\end{pmatrix} 

C^2_5 

{5 \choose 2} 

\tbinom{5}{2} 
I want to get a standard input on the number of combinations

**Comment by OrangeX4** [comment]
Now you can use `{5 \choose 2}`.

Update by `pip install latex2sympy2==1.7.9`.
