### ISSUE TITLE
Which line would i need to change to make it work in every file extension?

### ISSUE THREAD

**Issue by martinpflaum** [OrangeX4/Latex-Sympy-Calculator#18]
Hey, I really like ur plugin! currently its only working in .tex files. I want to also use it in c++ with some other plugin to view to latex. 

Which line would i need to change to make it work in every file-extension?

**Comment by OrangeX4** [comment]
Fixed it.

Update the extension and you can test it.

**Comment by martinpflaum** [comment]
Wow that was fast! Thanks a lot😊👍
