### ISSUE TITLE
数学环境不稳定

### ISSUE THREAD

**Issue by yixing312** [OrangeX4/Latex-Sympy-Calculator#20]
在编写过程中经常会出现数学环境被反包的情况，如图
![TARC$520@F3RC~{76Z~%%US](https://user-images.githubusercontent.com/96825143/207080914-b9049eba-b70a-4db7-9d96-cef0ef51ac9b.png)
插件将非数学环境的范围认定为数学环境而同时真正的数学环境中失去了插件的效果
这种问题可以通过重启软件解决，但是偶尔会经常发生在ipynb文件中
md文件中可以通过打开配置文件解决

**Comment by OrangeX4** [comment]
暂时没有找到原因，不过这个 issue 也许应该被移至 hsnips 仓库，而非这个仓库。
