### ISSUE TITLE
the example "\frac{d}{dx}(x^3+x^2+1)" in README.md seems to be wrong

### ISSUE THREAD

**Issue by ShiWenber** [OrangeX4/Latex-Sympy-Calculator#23]
```latex
% Before
\frac{d}{dx}(x^3+x^2+1)
```

I used the "Append result of selected expression" command, and obtained this:

```latex
% After
\frac{d}{dx}(x^3+x^2+1) = [ x]
```

However, when I used the command for this expression:

```latex
% Before 
\frac{d(x^3+x^2+1)}{dx}
```

I got the following correct result:

```latex
% After
\frac{d(x^3+x^2+1)}{dx} = x (3 x + 2)
```

Therefore, maybe the example should be corrected to

```latex
% Before 
\frac{d(x^3+x^2+1)}{dx}

% After
\frac{d(x^3+x^2+1)}{dx} = x (3 x + 2)
```

**Comment by OrangeX4** [comment]
I have fixed it. You can update by 'pip install latex2sympy2==1.9.1'.
