### ISSUE TITLE
arithmetic calculation of sqrt, log, and other functions 

### ISSUE THREAD

**Issue by lief-y** [OrangeX4/Latex-Sympy-Calculator#3]
For basic arithmetic calculations, it works well. However, it doesn't seem work well for functions.
Running the extension for `\frac{\ln2}{2}` returns `=\frac{\log{\left(2 \right)}}{2}` instead of  a number.
Similarly, running the extension for `\sin(1.2)` returns `=\sin{\left(\frac{6}{5} \right)}`.

Is there a way to make this great extension work for functions? Thank you!

**Comment by OrangeX4** [comment]
I have added this new function today. You can update your extension to 1.3.0 and use this function now.

You can press Shift + Ctrl + Alt + N (numerical) to get the numerical result of the selected Latex text. It will like:

```
# Before
\sqrt{2}

# After
\sqrt{2} = 1.41421356237310 
```

**Comment by lief-y** [comment]
Thank you for the quick reply!

I updated the extension to 1.3.0. and tried `Shift+Ctrl+Alt+N` and `Ctrl+P + LaTeX-Sympy-Calculator: Calculate Numeric...`, but no result returned.

Not sure, what's wrong with my system. I am using Windows 10 and installed Python 3.9.

**Comment by OrangeX4** [comment]
It is strange, it works well for me... I am using Windows 10 and Python 3.9 same with you.

Can you use other functions normally? Are there any error message?

**Comment by lief-y** [comment]
> It is strange, it works well for me... I am using Windows 10 and Python 3.9 same with you.
> 
> Can you use other functions normally? Are there any error message?

Yes. The `Shift+Ctrl+Alt+E` and `Shift+Ctrl+Alt+R` work fine. I didn't try running Python code.
Is there a specific package that I should import before using `Shift+Ctrl+Alt+N`?

**Comment by OrangeX4** [comment]
No, there is nothing else to be installed. Arithmetic calculation is a normal function of sympy, you can calculate it by 
execute `latex2sympy("\sqrt{2}").evalf()` python code.

I haven't found the possible reasons for it.

**Comment by lief-y** [comment]
I restarted the computer, now it works. Thank you for creating this awesome extension!

**Comment by OrangeX4** [comment]
Well, you are welcome.
