### ISSUE TITLE
如何添加自定义的语法

### ISSUE THREAD

**Issue by pilgrimlyieu** [OrangeX4/Latex-Sympy-Calculator#4]
因为我平时使用分式用的是dfrac，同时还有一些整合的宏，因此默认的语法不能满足我的需求。

我尝试修改[这个](https://github.com/OrangeX4/latex2sympy)里面的PS.g4文件，并进行了安装，但似乎没有生效。由于我不是很懂，所以我也不知道我做的对不对。

另外我也想知道如何修改输出的内容，例如我想把输出的分式也转成dfrac。

非常感谢！

**Comment by OrangeX4** [comment]
如果只是简单的语法更换, 可以考虑不用修改 PS.g4 文件里的语法, 使用简单正则表达式替换即可.

例如, 在输入前, 用 python 自带的文本替换语法 `r"\frac{1}{2}".replace("frac", "dfrac", -1)` 替换成 dfrac, 再输出时再替换回 frac 就好.

**Comment by pilgrimlyieu** [comment]
好的非常感谢！已经成功了。
不过微分算子d的替换有点困难，我自定义了一个罗马体的\d宏，但是输出替换时似乎有点困难
