### ISSUE TITLE
Probably a very simple issue

### ISSUE THREAD

**Issue by Therrk** [OrangeX4/Latex-Sympy-Calculator#5]
This is probably a very simple issue, and it's very probably some user error on my part.

I'm currently on a system running Linux Mint, trying to set up this extention. I've created a virtual environnement where I've installed latex2sympy2 and Flask. I've selected the Python interpreter linked to that virtual environnement. I've tried to write equations all the different ways I know of, but whenever I select some equation and hit Shift + Ctrl + Alt + E, or any other key configuration that the  VS Code page talks about, nothing happens, I get no error message, no log file, as far as I'm aware, my machine might not have registered the imput at all.

That's also probably not enough detail, but I don't really know what to add more.

**Comment by OrangeX4** [comment]
The VSCode will call the function with command like "python3 xxx.py". So the python and packages are supposed to be installed globally.

Besides, it uses different commands in different systems, like linux and macos to "python3" and windows to "python". I am not sure if Linux Mint is recognized as Linux.
