### ISSUE TITLE
Bug report: Could not recognize letter 'r'

### ISSUE THREAD

**Issue by Na2CuCl4** [OrangeX4/Latex-Sympy-Calculator#6]
I report a strange bug here...
When there exists a **letter** `r` in the expression **except for** `\right`, the calculator could not evaluate it, like (➡️ means after pressing Ctrl + Shift + Alt + E)
- `a*a` ➡️ `a*a=a^{2}`
- `r*r` ➡️ Message "I expected something else here r*r ^"
- `\left(a\right)*a` ➡️ `\left(a\right)*a=a^{2}`
- `\int_0^{+\infty}e^{-x}dx` ➡️ `\int_0^{+\infty}e^{-x}dx=1`
- `\int_0^{+\infty}e^{-r}dr` ➡️ Message "I expected something else here \int_0^{+\infty}e^{-r}dr ~~~~~~~~~~~~~~~~~~~~^"
- `\int_0^r e^{-x}dx` ➡️ Message "I expected something else here \int_0^re^{-x}dx ~~~~~~~^"
- `\int_0^a e^{-x}dx` ➡️ `\int_0^a e^{-x}dx=1 - e^{- a}`

**Anyway, this extension is amazing!** Yet please help to fix this bug, thanks a lot!

**Comment by OrangeX4** [comment]
It is a bug and I found it some months ago. But I can't figure it out after several times of tries.

You can substitute it with other letters like `\rho`.

I am sorry about it :-(

**Comment by Na2CuCl4** [comment]
I tried to track why it couldn't recognize 'r', yet I failed, either. 

Could we **avoid reading letter 'r' by replace it with something else**? Like an unused Greek alphabet. 
I think **it is necessary**, since 'r' is frequently used in physics articles. 
Therefore, I modified function `latex2latex` in package `latex2sympy2`. 
```
# Updated by Na2CuCl4
def latex2latex(tex):
    # All supported Greek alphabets
    replacement = [ r'\alpha', r'\beta', r'\gamma', r'\delta', r'\epsilon', r'\varepsilon', r'\zeta', r'\eta', r'\theta', r'\vartheta', r'\iota', r'\kappa', r'\lambda', r'\mu', r'\nu', r'\xi', r'\pi', r'\varpi', r'\rho', r'\varrho', r'\sigma', r'\varsigma', r'\tau', r'\upsilon', r'\phi', r'\varphi', r'\chi', r'\psi', r'\omega', r'\Gamma', r'\Delta', r'\Theta', r'\Lambda', r'\Xi', r'\Pi', r'\Sigma', r'\Upsilon', r'\Phi', r'\Psi', r'\Omega' ]

    # Replace r with another symbol
    replaced = ""
    for expr in replacement:
        if tex.find(expr) == -1:
            replaced = expr
            tex = tex.replace('r', expr, -1)
            tex = tex.replace('\\' + expr + 'ho', r'\rho', -1)
            tex = tex.replace('\\' + expr + 'ight', r'\right', -1)
            tex = tex.replace('\\f' + expr + 'ac', r'\frac', -1)
            tex = tex.replace('\\math' + expr + 'm', r'\mathrm', -1)
            tex = tex.replace('{\\' + expr + 'm d}', r'{\rm d}', -1)
            break

    # Evaluation
    res = sympy.latex(simplify(latex2sympy(tex).subs(variances).doit().doit())).replace(r'\left[\begin{matrix}', r'\begin{bmatrix}', -1).replace(r'\end{matrix}\right]', r'\end{bmatrix}', -1)

    # Modify the result
    if replaced == "":
        return res
    else:
        return res.replace(replaced, 'r', -1)
```
It works well. I do believe it works most of the time, since nobody would enter an expression containing all Greek alphabets... 😝

**Comment by OrangeX4** [comment]
Thanks, I think it is a great trick.

But I can't merge it into the master branch because I am worry about that there are some unpredictable cases with letter 'r'.

You can use it for yourself temporarily. I will try to find a better way to fix it. Thanks.

**Comment by Na2CuCl4** [comment]
Yeah, I know there might well be an unexpected 'r'... Yet let's think about it from another way.
When couldn't 'r' be replaced? **Only when 'r' is used in a LaTeX command**. What is special about commands? **They all start with a backslash**, and except for several symbols like `\#`, `\,` etc., **they are all composed of alphabets and numbers** (Click [here](https://www.bu.edu/math/files/2013/08/LongTeX1.pdf) to see all common commands in LaTeX). So why couldn't we write the replace algorithm like this? 
```
# Updated by Na2CuCl4
def latex2latex(tex):
    # All supported Greek alphabets
    replacement = [ r'\alpha', r'\beta', r'\gamma', r'\delta', r'\epsilon', r'\varepsilon', r'\zeta', r'\eta', r'\theta', r'\vartheta', r'\iota', r'\kappa', r'\lambda', r'\mu', r'\nu', r'\xi', r'\pi', r'\varpi', r'\rho', r'\varrho', r'\sigma', r'\varsigma', r'\tau', r'\upsilon', r'\phi', r'\varphi', r'\chi', r'\psi', r'\omega', r'\Gamma', r'\Delta', r'\Theta', r'\Lambda', r'\Xi', r'\Pi', r'\Sigma', r'\Upsilon', r'\Phi', r'\Psi', r'\Omega' ]

    # Replace r with another symbol
    replaced = ""
    newTex = ""
    for expr in replacement:
        if tex.find(expr) == -1:
            replaced = expr
            TexCmd = False # If it is a LaTeX command
            for ch in tex:
                if ch == '\\':
                    if TexCmd: TexCmd = False # Line break
                    else: TexCmd = True # New command
                    newTex += ch
                elif ch.isalnum() and TexCmd: # Still a command
                    newTex += ch
                else: # Not a command
                    TexCmd = False
                    if ch == 'r': # Replace
                        newTex += replaced + ' '
                    else:
                        newTex += ch
            break
    if replaced == "": newTex = tex

    # Evaluation
    newTex = sympy.latex(simplify(latex2sympy(newTex).subs(variances).doit().doit())).replace(r'\left[\begin{matrix}', r'\begin{bmatrix}', -1).replace(r'\end{matrix}\right]', r'\end{bmatrix}', -1)

    # Modify the result
    if replaced == "":
        return newTex
    else:
        return newTex.replace(replaced, 'r', -1)
```
This will not involve any unexpected 'r'. Hope it might help!

**Comment by OrangeX4** [comment]
It is great and works well for me. Thanks for your contribution.

I have already added it into the package and published it.

You can update it:

``` sh
pip uninstall latex2sympy2
pip install latex2sympy2==1.6.6
```

At the end, thanks a lot!

**Comment by OrangeX4** [comment]
There is a bug that it misunderstands `\begin{pmatrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \\\end{pmatrix}`.

**Comment by Na2CuCl4** [comment]
Got it. 

Is `\begin{environment} ... \end{environment}` the only command with irreplacable arguments in math mode? If so, we could fix this bug by directly add this to a so-called 'exception list'. 

By the way, could I commit my changes to the github page of `latex2sympy2` [here](https://github.com/OrangeX4/latex2sympy)? It seems that you didn't merge your changes into it, since the latest change is 5 months ago.

**Comment by OrangeX4** [comment]
I am sorry that I forgot to push it to github. I will push it a moment later, so please wait for it.

Welcome for your PR, thanks!

**Comment by OrangeX4** [comment]
I have pushed it.
