### ISSUE TITLE
Does not work even if having installed the required packages

### ISSUE THREAD

**Issue by LeetaH666** [OrangeX4/Latex-Sympy-Calculator#9]
I used the plugin several months ago and it worked. However, there might be something changed in my computer. Now when I use the plugin, VSCode would inform me as follows:

    Notifications: 
    Running python failed... Please make sure you have install "python", "latex2sympy2" and "Flask"

I use a conda environment and the terminal would activate the conda environment by default. I have checked that the following codes work in the terminal both in and out of the conda environment: 

    python
    import latex2sympy2
    import flask

Should I install a python and install the required packages out of the conda environment or is there any way to link my python path to the plugin (I find nothing about the plugin in the settings)?
Note: It worked before!

**Comment by OrangeX4** [comment]
Are you using Windows? or Linux?

In windows, the extension will run `python server.py` and activate the server. In Linux, it run `python3 server.py` instead.

Of course, you install a python out of the conda environment will solve the problem.

And I have already updated the extension to 1.4.3 so you can configure your python path by `Ctrl + ,` and search `latex-sympy-calculator`.

**Comment by LeetaH666** [comment]
Well, actually the issue is not about the python path 🤣. 

I have checked the code in [extension.js](https://github.com/OrangeX4/Latex-Sympy-Calculator/blob/main/extension.js). It seems it sends the same error notification to every types of error. Actually the error comes due to the update of _latex-sympy-calculator_. The "factor" module in _latex2sympy2_ is not available for version==1.6.8 (which is my version before). Now I update it to version==1.6.16 and it works!

I think the error notification is too vague 🤔. Anyway, thanks for ur patience and ur contribution! The plugin is 👍.

**Comment by OrangeX4** [comment]
I am sorry about that I forgot that pip will not update `latex2sympy2` automatically.

I have updated the error notification to inform all users.

Thanks!
